#!/usr/bin/env python3
"""mask-manifest.json -> docs/feasibility-results.md (no hand-entered numbers).

The feasibility gate (docs/feasibility.md): does the mask method produce topology
the boxes do not? Reported as the fraction of box-carrying images where the
generated mask's total Betti numbers differ from the box-fill mask's, plus a
per-class breakdown.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def build(manifest_path: Path) -> str:
    m = json.loads(manifest_path.read_text())
    n_box = m["images_with_boxes"]
    changed = m["images_where_method_changed_topology_vs_boxfill"]
    d_beta1_total = sum(r["betti_drift_vs_boxfill"]["d_beta1"] for r in m["records"])
    methods: dict[str, int] = {}
    for r in m["records"]:
        methods[r["method"]] = methods.get(r["method"], 0) + 1

    src_line = (
        f"Source: `{m['images_dir']}` · method `{m['method']}` · "
        f"{m['images']} images ({n_box} with boxes)."
    )
    fallback_line = (
        f"GrabCut collapsed on >=1 box (and fell back to a rectangle for that box) on "
        f"**{methods.get('grabcut+boxfill', 0)} / {m['images']}** images -- COCO's cluttered, "
        "overlapping-box scenes are the hard case; WSD spacecraft on dark space should fall "
        "back far less often."
    )
    lines = [
        "# Feasibility results -- box -> mask topology drift",
        "",
        "Generated by `seg_masks/scripts/feasibility_report.py`. Do not hand-edit.",
        "",
        src_line,
        "",
        f"Per-image method used: {methods} (`grabcut+boxfill` = GrabCut collapsed on a box).",
        "",
        "## Does the mask carry topology the box does not?",
        "",
        "| metric | value |",
        "|---|--:|",
        (
            f"| images where mask Betti != box-fill Betti | "
            f"**{changed} / {n_box}** ({changed / max(1, n_box):.1%}) |"
        ),
        f"| total beta1 (holes) introduced vs box-fill | {d_beta1_total} |",
        "",
        fallback_line,
        "",
        "## Top classes by images where topology changed",
        "",
        "| class id | images | changed | Σ Δβ₁ |",
        "|--:|--:|--:|--:|",
    ]
    top = sorted(
        m["per_class_drift"].items(),
        key=lambda kv: (-kv[1]["changed"], -kv[1]["d_beta1"]),
    )[:12]
    for cid, v in top:
        lines.append(f"| {cid} | {v['images']} | {v['changed']} | {v['d_beta1']} |")
    lines += [
        "",
        "## Gate",
        "",
        "`docs/feasibility.md`: proceed to a segmentation head if the mask changes the",
        "topology on a meaningful fraction of images (target > 20%, concentrated in",
        "`solar`/`antenna` for WSD). Otherwise stay on branch",
        "`topo-prune/certified-detection`. **This run is on COCO128 as a pipeline",
        "check** — the real gate needs the WSD export (`../REPO_MAP.md` B2).",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("artifacts/masks/train/mask-manifest.json")
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("seg_masks/docs/feasibility-results.md")
    out.write_text(build(src), encoding="utf-8")
    print(f"wrote {out}")
