"""Build Markdown result tables from experiment ``run.json`` manifests.

``CLAUDE.md``: every number in a results table is generated from a manifest, never
hand-entered. ``python -m topo_prune.report [runs_dir] [out.md]`` regenerates
``topo_prune/docs/p1-results.md``.
"""

from __future__ import annotations

import json
from pathlib import Path


def _f(x, spec="{:.3f}"):
    return "—" if x is None else spec.format(x)


def e1_table(m: dict) -> str:
    head = (
        f"Run `{m['utc']}` · weights `{m['weights']}` · conf={m['operating_point_conf']} "
        f"(tau={m['tau_logit']:.3f}) · {m['n_calib']} calib / {m['n_test']} test images · "
        f"nc={m['nc']} · Python {m.get('python', '?')}"
    )
    cols = (
        "| method | budget | actual | eps_emp med | eps_cert med | looseness | "
        "cov@eps_emp | cov@eps_cert | audited | Betti-changed | viol@eps_emp | "
        "viol@eps_cert | eps_emp held OOD |"
    )
    rule = "|---|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|:--:|"
    rows = [
        (
            f"| {a['method']} | {a['target_fraction']:.0%} | {a['actual_fraction']:.2f} "
            f"| {_f(a['epsilon_empirical_median'], '{:.2f}')} "
            f"| {_f(a['epsilon_certified_median'], '{:.2f}')} "
            f"| {_f(a['looseness_median'], '{:.2f}')}x "
            f"| {a['coverage_empirical']:.1%} | {a['coverage_certified']:.1%} "
            f"| {a['audited_triples']} | {a['betti_changed_triples']} "
            f"| {a['violations_empirical']} | **{a['violations_certified']}** "
            f"| {'yes' if a['empirical_bound_held_on_test'] else 'no'} |"
        )
        for a in m["arms"]
    ]
    return "\n".join([head, "", f"> {m['note']}", "", cols, rule, *rows])


def p15_table(m: dict) -> str:
    t = m["targeted_bridge_check"]
    head = (
        f"Run `{m['utc']}` · {m['n_scenes']} synthetic scenes ({m['grid_size']}^2 grid) · "
        f"{m['perturbation']} · constructed-vs-computed Betti mismatches: "
        f"**{m['constructed_vs_computed_betti_mismatches']}/{m['n_scenes']}**"
    )
    cols = "| delta (sup-norm) | audited triples | coverage | violations | perturbations that changed Betti |"
    rule = "|--:|--:|--:|--:|--:|"
    rows = [
        (
            f"| {r['delta']:.2f} | {r['triples']} | {r['coverage']:.1%} | "
            f"**{r['violations']}** | {r['perturbed_betti_changed']}/{r['triples']} |"
        )
        for r in m["deltas"]
    ]
    tail = (
        f"Targeted bridge check: of **{t['cases']}** multi-component scenes, a merge "
        f"perturbation changed Betti on **{t['betti_actually_changed']}** and was "
        f"certified as topology-preserving on **{t['certified']}**."
    )
    return "\n".join([head, "", cols, rule, *rows, "", tail])


def latest(runs_dir: Path, prefix: str) -> dict:
    files = sorted(runs_dir.glob(f"{prefix}*.json"))
    if not files:
        raise FileNotFoundError(f"no {prefix}*.json under {runs_dir}")
    return json.loads(files[-1].read_text())


def build_p1_results(runs_dir: Path) -> str:
    e1, e2 = latest(runs_dir, "run_"), latest(runs_dir, "synthetic_")
    preamble = (
        "# P1 results -- certified topological pruning on a detector\n\n"
        "Generated by `topo_prune/src/topo_prune/report.py` from the JSON manifests in\n"
        "`experiments/p1_certificate/runs/`. Do not hand-edit the tables.\n\n"
        "The **`viol@eps_cert` column is the plan's falsifiable prediction** (§3.4): on\n"
        "every certified triple the pruned model's Betti numbers must equal the unpruned\n"
        "model's. Expected value 0."
    )
    n_held = sum(1 for a in e1["arms"] if a["empirical_bound_held_on_test"])
    e1_note = (
        "`eps_emp` (max sup-norm gap over the *calibration* split) is **not** a\n"
        "certificate: on "
        f"{len(e1['arms']) - n_held}/{len(e1['arms'])} arms the calibration `eps_emp` was\n"
        "smaller than some test-split perturbation it was meant to bound (`eps_emp held\n"
        "OOD` = no), and every `viol@eps_emp` is exactly such an out-of-distribution case\n"
        "(`epsilon_bounded_the_gap: false` in the manifest). `eps_cert` (closed-form\n"
        "single-layer Lipschitz bound over the final classification conv x calibration-max\n"
        "penultimate activation, `DEVIATIONS.md` D1.4 / D6) is a calibration-based\n"
        "high-confidence bound, ~2-5x looser, and audits clean on every arm."
    )
    return "\n\n".join([
        preamble,
        "## E1 -- falsification audit on a really-pruned YOLO26n",
        e1_table(e1),
        e1_note,
        "## E2 (P1.5) -- synthetic validation, exact ground-truth homology",
        p15_table(e2),
    ]) + "\n"


if __name__ == "__main__":
    import sys

    runs = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(
        "topo_prune/experiments/p1_certificate/runs"
    )
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("topo_prune/docs/p1-results.md")
    out.write_text(build_p1_results(runs), encoding="utf-8")
    print(f"wrote {out}")
